---
- name: Listen for events using the event source plugin
  hosts: all
  
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{dt_api_host}}"
        dt_api_token: "{{dt_api_token}}"
        delay: 60

  rules:
    - name: Problem payload Dynatrace for CPU issue
      condition: event.payload.problemTitle contains "CPU saturation"
      action:
        run_job_template:
          name: "Remediate CPU saturation issue"
          organization: "Default"
    
    - name: Problem payload Dynatrace for App Failure rate increase issue
      condition: event.payload.problemTitle contains "Failure rate increase"
      action:
        run_job_template:
          name: "Remediate Failure rate increase EC2"
          organization: "Default"
    
    - name: Problem payload Dynatrace for DB Failure
      condition: 'event.payload.problemTitle contains "3 services: Failure rate increase"'
      action:
        run_job_template:
          name: "Remediate Failure rate increase for Easytrade DB"
          organization: "Default"
