---
- name: Listen for events using the event source plugin
  hosts: all
  
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_api_url }}"
        dt_api_token: "{{ dynatrace_api_token }}"
        delay: 60

  rules:
    - name: Problem payload Dynatrace for Easytrade DB Failure
      #condition: event.title is match("Failure rate increase")
      condition: (event.title == "JavaScript error rate increase" or event.title == "Failure rate increase") and (event.impactedEntities[0].name == "BrokerService" or event.impactedEntities[0].name == "TradeManagement")
      action:
        run_job_template:
          name: "Remediate Failure rate for Easytrade DB"
          organization: "Default"
