---
-
  hosts: localhost
  name: "Initiate Failure rate for Easytrade DB"
  tasks:
    
    - name: Call easytrade DB service to apply configuration change
      shell: "curl -X PUT '{{dt_easytrade_url}}/feature-flag-service/v1/flags/db_not_responding' -H 'Content-Type: application/json'  -d '{\"enabled\": \"true\"}'"

