---
- hosts: localhost
  name: "easytrade-break"
  tasks:

    - name: Call easytrade DB service to apply configuration change
      shell: >
        curl -X PUT 'http://easytrade-frontend-easytrade.apps.cluster-qgxw5.dynamic.redhatworkshops.io/feature-flag-service/v1/flags/credit_card_meltdown'
        -H 'Content-Type: application/json'
        -d '{"enabled": true}'
