---
-
  hosts: localhost
  name: "create-easytrade-memory-contention"
  vars:
    deployment_name: accountservice
    namespace: easytrade
    container_name: accountservice

    resource_limit_memory: 100Mi
    resource_request_memory: 100Mi

  tasks:

    - name: Authenticate to OpenShift
      openshift_auth:
        host: "{{ openshift_api_url }}"
        api_key: "{{ openshift_api_token }}"
        validate_certs: false

    - name: Adjust deployment limits
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
            namespace: "{{ namespace }}"
          spec:
            template:
              spec:
                containers:
                  - name: "{{ container_name }}"
                    resources:
                      limits:
                        memory: "{{ resource_limit_memory }}"
  

