---
- hosts: localhost
  name: "Remediate Credit Card Order Service Issue"

  vars:
    feature_flag_url: "http://easytrade-frontend-easytrade.apps.cluster-qgxw5.dynamic.redhatworkshops.io/feature-flag-service/v1/flags/credit_card_meltdown"

  tasks:

    - name: Print incoming Dynatrace problem ID (EDA triggered)
      debug:
        msg: "Received problemId: {{ ansible_eda.event.problemId }}"
      when: ansible_eda is defined and ansible_eda.event is defined and 'problemId' in ansible_eda.event

    - name: Post comment to Dynatrace - remediation initiated
      shell: >
        curl -X POST 
        --header 'Authorization: Api-Token {{ dt_api_token }}' 
        -H 'Content-Type: application/json' 
        -d '{"message": "Remediation triggered for credit card order issue via Ansible EDA"}' 
        {{ dt_api_url }}/api/v2/problems/{{ ansible_eda.event.problemId }}/comments
      when: ansible_eda is defined and ansible_eda.event is defined and 'problemId' in ansible_eda.event

    - name: Trigger remediation by enabling feature flag
      shell: >
        curl -X PUT '{{ feature_flag_url }}'
        -H 'Content-Type: application/json'
        -d '{"enabled": true}'

    - name: Post comment to Dynatrace - remediation complete
      shell: >
        curl -X POST 
        --header 'Authorization: Api-Token {{ dt_api_token }}' 
        -H 'Content-Type: application/json' 
        -d '{"message": "Successfully remediated credit card order service issue via Ansible"}' 
        {{ dt_api_url }}/api/v2/problems/{{ ansible_eda.event.problemId }}/comments
      when: ansible_eda is defined and ansible_eda.event is defined and 'problemId' in ansible_eda.event
